services:
  - type: web
    name: internal-helpdesk-api
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build --workspace=apps/api
    startCommand: node apps/api/dist/main.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: HOST
        value: 0.0.0.0
      - key: PUBLIC_API_URL
        value: https://internal-helpdesk-api.onrender.com
      - key: FRONTEND_URL
        value: https://internal-help-desk-web-q2fw.vercel.app
