export const MOCK_CALENDAR_EVENTS = [
  {
    id: 'mock-1',
    title: 'Team Standup',
    description: 'Daily sync with the engineering team. Review blockers and sprint progress.',
    start: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    end: new Date(Date.now() + 2.5 * 60 * 60 * 1000).toISOString(),
    location: 'Google Meet',
    htmlLink: 'https://calendar.google.com',
    meetLink: 'https://meet.google.com/abc-defg-hij',
    meetCode: 'abc-defg-hij',
    allDay: false,
    organizerName: 'Fahad Nadeem',
    organizerEmail: 'nfahad4787@gmail.com',
    attendeeCount: 5,
  },
  {
    id: 'mock-2',
    title: 'HR Policy Review',
    description: 'Quarterly review of updated HR policies and employee handbook changes.',
    start: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    end: new Date(Date.now() + 25 * 60 * 60 * 1000).toISOString(),
    location: 'Google Meet',
    htmlLink: 'https://calendar.google.com',
    meetLink: 'https://meet.google.com/klm-nopq-rst',
    meetCode: 'klm-nopq-rst',
    allDay: false,
    organizerName: 'HR Team',
    organizerEmail: 'hr@company.com',
    attendeeCount: 8,
  },
  {
    id: 'mock-3',
    title: 'Company All-Hands',
    description: 'Monthly company-wide update with leadership Q&A.',
    start: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    end: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000).toISOString(),
    location: 'Google Meet',
    htmlLink: 'https://calendar.google.com',
    meetLink: 'https://meet.google.com/uvw-xyza-bcd',
    meetCode: 'uvw-xyza-bcd',
    allDay: false,
    organizerName: 'Leadership',
    organizerEmail: 'ceo@company.com',
    attendeeCount: 42,
  },
];
